

default_platform(:ios)

desc "Run Tests & Increase Build number"
  lane :oncommit do
    scan(scheme: "ActionOne") # Name of the scema to be tested
    increment_build_number
  end

  desc "Run Tests & Increase Build number and update patch version number"
  lane :onpatchmerge do
    scan(scheme: "ActionOne") # Name of the scema to be tested
    increment_build_number
    increment_version_number_in_xcodeproj
  end

  desc "Run Tests & Increase Build number and update Minor version number"
  lane :onminormerge do
    scan(scheme: "ActionOne") # Name of the scema to be tested
    increment_build_number
    increment_version_number_in_xcodeproj(
      bump_type: 'minor' # Automatically increment minor version number
    )
  end

  desc "Run Tests & Increase Build number and update Major version number"
  lane :onmajormerge do
    scan(scheme: "ActionOne") # Name of the scema to be tested
    increment_build_number
    increment_version_number_in_xcodeproj(
      bump_type: 'major' # Automatically increment major version number
    )
  end

  desc "Increment patch version"
  lane :incrementpatch do
    increment_version_number_in_xcodeproj
  end
  desc "Increment minor version"
  lane :incrementminor do
    increment_version_number_in_xcodeproj(
      bump_type: 'minor' # Automatically increment minor version number
    )
  end
  desc "Increment Major version"
  lane :incrementmajor do
    increment_version_number_in_xcodeproj(
      bump_type: 'major' # Automatically increment major version number
    )
  end
end
